### ISSUE TITLE
[BUG] Emojis visible in spoiler text

### ISSUE THREAD

**Issue by bohrabhijeet** [laurencedawson/sync-for-reddit#1167]
**Spotted on**
https://www.reddit.com/r/redditsync/comments/ud7azw

**Comment by laurencedawson** [comment]
Fixed for the next release.

**Comment by RobinHeidenis** [comment]
I am still experiencing this issue on v22.06.17-16:57 (22050)

Spotted [here](https://www.reddit.com/r/StrangerThings/comments/w9sves/lmaooo/ihyftnp/)

![Screenshot_20220728-121204.jpg](https://user-images.githubusercontent.com/29160608/181494116-d9dcf2e7-45fe-49b8-9860-4c63899d736f.jpg)

Let me know if you need more information

**Comment by kristianka** [comment]
Hi, still happens to me in v23.02.02-21:38. Seems to also happen in the official reddit app

**Comment by laurencedawson** [comment]
Issue is still open lol
