### ISSUE TITLE
Android navigation buttons are white-on-white in settings screen

### ISSUE THREAD

**Issue by zamuz** [laurencedawson/sync-for-reddit#160]
Android navigation buttons are white on a white background on beta 3. (Galaxy S9+, Android 10)
![Screenshot_20200606-213618_Sync Dev](https://user-images.githubusercontent.com/731751/83958296-01cef300-a83e-11ea-95da-77c2578c3b7b.jpg)

**Comment by zamuz** [comment]
This is still an issue on beta 7.

**Comment by zamuz** [comment]
This is still an issue on beta 12.

**Comment by laurencedawson** [comment]
Fixed for the next release.

**Comment by zamuz** [comment]
Hey, I just updated both Sync Dev and Pro to beta 19 and sadly this is still an issue, screenshot attached. ![Screenshot_20200919-203247_Sync Dev](https://user-images.githubusercontent.com/731751/93691112-4c0b7580-fab7-11ea-8bd2-f27e9c1b673e.jpg)
