### ISSUE TITLE
[BUG] Favorite a sub you don't subscribe to, and it's lost on app restart

### ISSUE THREAD

**Issue by nathan-sav** [laurencedawson/sync-for-reddit#254]
**Describe the bug**

If you favorite a sub that you don't subscribe to it'll be shown in the favorites section, but is lost on app restart.

**To Reproduce**
1. Go to a specific subreddit
2. Hit sidebar at the top
3. Hit favorite
4. Hit back
5. Hit subs at the bottom and confirm it's listed under favorites
6. Kill the app
7. Reopen it, go to subs, and it'll no longer be listed as a favorite

**Comment by laurencedawson** [comment]
This has been fixed foe the next release.

**Comment by geominorai** [comment]
This issue is still present on V20 beta 6 if you are not logged in.
