### ISSUE TITLE
[BUG] Inconsistensies with alignment of text and items in flairs/awards pills

### ISSUE THREAD

**Issue by PrebbLord** [laurencedawson/sync-for-reddit#565]
**Describe the bug**
The text on the modern flair pills isn't centered vertically, and isn't lined up with the text on the awards pill.

![image](https://user-images.githubusercontent.com/7637583/107133257-3655fa00-694b-11eb-86b8-def3d649d36f.png)

**Comment by laurencedawson** [comment]
Fixed by reducing the size of the images ever so slightly

**Comment by PrebbLord** [comment]
I know it's super nitpicky but these still don't seem to line up right. The post flairs seem to only be centered vertically some of the time. The awards one is always too low I think. Tried with different fonts and sizes and none of them seem to sit right. This is on beta 32.
![Screenshot_20210211-111210_Sync](https://user-images.githubusercontent.com/7637583/107585676-8b538200-6c63-11eb-9c6d-8f2c87ca75f8.jpg)

**Comment by PrebbLord** [comment]
Here's one that's too low, then the awards pill has an issue here, too
![Screenshot1](https://user-images.githubusercontent.com/7637583/107586202-5d227200-6c64-11eb-9668-03136f516c40.jpg)

**Comment by PrebbLord** [comment]
Here's a really bad offender, text cuts off heaps and awards aren't shown at all.
![image](https://user-images.githubusercontent.com/7637583/108022946-72ddd000-7086-11eb-8a8f-93f036941568.png)

**Comment by PrebbLord** [comment]
Same issue on beta 33
![image](https://user-images.githubusercontent.com/7637583/108067368-8a887900-70c5-11eb-8829-0770a9028625.png)

**Comment by laurencedawson** [comment]
Can you include links to the posts please

**Comment by laurencedawson** [comment]
Alright added a few fixes for this for beta 34.

**Comment by laurencedawson** [comment]
Hopefully fixed! What a ball ache

**Comment by PrebbLord** [comment]
Here's the link to the worst one if you wanted to test.
https://www.reddit.com/r/ihaveihaveihavereddit/comments/lksi0t/fuckin_piitna/
