### ISSUE TITLE
[BUG] Data Saving Mode

### ISSUE THREAD

**Issue by Elite911** [laurencedawson/sync-for-reddit#930]
**Describe the bug**
In Data Saving mode you can still see images and thumbnails being loaded in cards mode for any i.reddit or v.reddit posts.

**To Reproduce**
1. Go to Settings
2. Click on DataOptions
3. Enable Data Saving Mode Aggressive
4. See frontpage / all / popular

**Expected behavior**
Images / thumbnails shouldn't be viewable until you tap into the post itself like older versions.

**Screenshots**
![Screenshot_20220327-214206_Sync_1](https://user-images.githubusercontent.com/5841305/160278835-ce61762e-226a-4cbb-af7e-ae4c82dae6d2.jpg)

**Smartphone (please complete the following information):**
 - Device: S21 Ultra
 - OS: Android 12
 - Browser SyncReddit
 - Version 22.3.24

**Additional context**
When updating to V22 I noticed all the thumbnails were being loaded in cards view. On the older version it never happened as using aggressive mode was supposed to stop it until you go into the actual post. I also did notice some posts with any i.reddit or v.reddit had a blank picture when scrolling through posts but majority did have the thumbnail visible.

**Comment by laurencedawson** [comment]
Fixed for the next release.

**Comment by Elite911** [comment]
Hello, Laurence,

Unfortunately the issue is still there for me. I noticed one change is that whenever you tap into the post the image is blocked but when scrolling it's still showing.

I'm on version v22.3.31.

![Screenshot_20220405-033051_Sync](https://user-images.githubusercontent.com/5841305/161604409-7d296c1f-672d-48c8-94ab-8d6195323f2c.jpg)
![Screenshot_20220405-033055_Sync](https://user-images.githubusercontent.com/5841305/161604419-a194da47-1e1d-4759-bcf0-489cbbda35f0.jpg)
